name: Run Lint Workflow
on:
  pull_request:
    types: [opened, synchronize]
    branches: ["main", "develop" , "release/*"]
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Run lint
        run: npm run lint
